version: "3.8"
name: mybentoo

services:
  database:
    image: postgres:12.3
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    networks:
      - backend

  redis:
    image: redis:6.0.5
    restart: unless-stopped
    ports:
      - ${REDIS_PORT:-6379}:6379
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - backend

  backend:
    build:
      context: ./apps/MyBentoo-Backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    depends_on:
      - database
      - redis
    networks:
      - backend

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./apps/MyBentoo-Frontend/dist:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
