name: Deploy MyBentoo

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "BRANCH=main" >> $GITHUB_ENV
            echo "ENV=prod" >> $GITHUB_ENV
            echo "DEPLOY_DIR=/var/www/MyBentoo" >> $GITHUB_ENV
          else
            echo "BRANCH=develop" >> $GITHUB_ENV
            echo "ENV=preprod" >> $GITHUB_ENV
            echo "DEPLOY_DIR=/var/www/MyBentoo-preprod" >> $GITHUB_ENV
          fi

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: bash /var/www/MyBentoo/scripts/deploy.sh ${{ env.ENV }}
